name: Server Deployment

on:
  push:
    branches:
      - main

jobs:
  web-deploy:
    name: 🎉 Deploy
    runs-on: ubuntu-latest
    steps:
    - name: 🚚 Get latest code
      uses: actions/checkout@v4

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'
      
    - name: 🔨 Build Project
      run: |
        npm install
        npm run build
    
    
    - name: 📂 Sync files
      uses: SamKirkland/FTP-Deploy-Action@v4.3.5
      with:
        server: www.jumpintojob.com
        username: jumpinto
        password: ${{secrets.ftp_password}}
        server-dir: /frontend.jumpintojob.com/

        
  windows-deploy:
    runs-on: self-hosted
    steps:
      - name: Install dependencies (Optional)
        run: |
          git pull origin main
          docker compose down
          docker compose up --build -d
          docker compose exec backend composer install
          docker compose exec backend php artisan optimize:clear
          docker compose exec backend php artisan migrate:fresh --seed --force